security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Account\User
                property: username

    firewalls:
        dev:
            pattern: '^/(_profiler|_wdt|build)/'
            security: false
        main:
            pattern: ^/
            security: true
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: account_login
                check_path: account_login
                username_parameter: connect_user[username]
                password_parameter: connect_user[password]
                enable_csrf: true
                csrf_parameter: connect_user[_token]
                csrf_token_id: hub/login
                form_only: true
                post_only: true
            logout:
                path: account_logout
                target: home_index
                enable_csrf: true
                csrf_parameter: disconnect_user[_token]
                csrf_token_id: hub/logout
                invalidate_session: true
            login_throttling:
                max_attempts: 5          
                interval: '15 minutes'
            remember_me:
                signature_properties: ['password', 'dateUpdate']
                remember_me_parameter: connect_user[rememberMe]
                name: symfony_remember_me
                secure: auto
                samesite: lax
                httponly: true
                path: /
                lifetime: 2592000 # 30 days in seconds
            
    role_hierarchy:
        ROLE_HUB_USER: ~
        ROLE_HUB_ADMIN: ROLE_HUB_USER

    access_control:
        - { path: ^/account/login$, roles: [PUBLIC_ACCESS] }
        - { path: ^/account/check(.*)$, roles: [PUBLIC_ACCESS] }
        - { path: ^/account, roles: [ROLE_HUB_USER] }
        - { path: ^/admin, roles: [ROLE_HUB_ADMIN] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
