# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.name: '%env(string:APP_NAME)%'
    app.env: '%env(string:APP_ENV)%'

imports:
    - { resource: 'version.yaml' }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\ExtendedEntityUserProvider:
        arguments:
            $registry: '@doctrine'
            $classOrAlias: 'App\Entity\Account\User'
            $property: 'username'
            $managerName: null
            $appName: '%env(string:APP_NAME)%'

    App\Extension\EventExtension:
        tags: [kernel.event_subscriber]

    App\Form\:
        resource: '../src/Form'
        tags: ['form.type']
        arguments:
            $htmlValidation: '%env(bool:APP_HTML_VALIDATION)%'

    App\Form\Account\PasswordUserType:
        arguments:
            $htmlValidation: '%env(bool:APP_HTML_VALIDATION)%'
            $passwordMinStrength: '%env(int:APP_PASSWORD_MIN_STRENGTH)%'